# Generated by Django 3.0.7 on 2020-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique='True')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('registration_confirmation', models.BooleanField(default='False')),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
